real_effort2/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
from . import config as config_py
import random, json


doc = """
This is a game that combines elements of the Public Goods game and real-effort
transcription task into one. This game has 2 modes, one with transcription off and one 
with transcription on. In mode 1, where transcription mode is off, each player has a 
fixed income and must determine how much of his/her income to report. A tax of X% is
automatically collected from each player's reported income. The total tax collected is 
multiplied by a specified multiplier and then divided evenly among all players in the 
group. Each player's total money is the amount of income remaining after tax is deducted 
from their income plus his/her share of the total tax money.

In mode 2, Subjects are shown two images of incomprehensible text.
Subjects are required to transcribe (copy) the text into a text entry field.
The quality of a subject's transcription is measured by the
<a href="http://en.wikipedia.org/wiki/Levenshtein_distance">Levenshtein distance</a>.
The accuracy of the players' transcription of the second image ultimately determines
each person's initial income. The remainder of mode 2 follows mode 1.
"""


def levenshtein(a, b):
    """Calculates the Levenshtein distance between a and b."""
    n, m = len(a), len(b)
    if n > m:
        # Make sure n <= m, to use O(min(n, m)) space
        a, b = b, a
        n, m = m, n

    current = range(n + 1)

    for i in range(1, m + 1):
        previous, current = current, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete = previous[j] + 1, current[j - 1] + 1
            change = previous[j - 1]

            if a[j - 1] != b[i - 1]:
                change = change + 1
            current[j] = min(add, delete, change)

    return current[n]


def distance_and_ok(transcribed_text, reference_text, max_error_rate):
    error_threshold = len(reference_text) * max_error_rate
    distance = levenshtein(transcribed_text, reference_text)
    ok = distance <= error_threshold
    return distance, ok


def assign_dictator(dictators_in_session: list, groups_with_dicts: list, group_matrix: list) -> list:
    """
    Assigns a dictator to each group that requires one
    """
    print("----Assign dictator----")

    index = 0
    if len(dictators_in_session) > 0:
        print("Dictators in session: ", dictators_in_session)
        print("Groups with dictators: ", groups_with_dicts)
        print("Group matrix: ", group_matrix)        
        for dictator in dictators_in_session:
            print("---")
            print("Current dictator: ", dictator)
            group_index = groups_with_dicts[index] - 1 # getting index of group with dictator
            current_group = group_matrix[group_index]
            print("Group index: ", group_index)
            print("Group matrix before update: ", group_matrix)
            print("Current group: ", group_matrix[group_index])
            current_group.append(dictator) # adding the benevolent dictator to the group
            print("Group matrix after update: ", group_matrix)
            index += 1

            if index == len(groups_with_dicts) or \
               index == len(dictators_in_session) : # break if more dictators than groups or no more dictators
                return group_matrix, dictators_in_session[index:] # return group and non assigned dictators
    else: # if no dictators in session
        return group_matrix, []


class Constants(BaseConstants):

    name_in_url = 'real_effort'

    # The total number of dictionaries in the data list in config.py is the
    # number of game rounds
    num_rounds = config_py.num_rounds
    num_groups = len(config_py.data_grps)

    dictators_file = open("dictators.json", "r")
    dictators = json.loads(dictators_file.read())

    players_per_group = 5 # 5 in prod
    instructions_template = 'real_effort2/Instructions.html'
    info_code = 'real_effort/Code.html'

    # List of the incomprehensible text that the players must transcribe
    reference_texts = [
        "Revealed preference",
        "Hex ton satoha egavecen. Loh ta receso minenes da linoyiy xese coreliet ocotine! Senuh asud tu bubo "
        "tixorut sola, bo ipacape le rorisin lesiku etutale saseriec niyacin ponim na. Ri arariye senayi esoced "
        "behin? Tefid oveve duk mosar rototo buc: Leseri binin nolelar sise etolegus ibosa farare. Desac eno "
        "titeda res vab no mes!",
    ]

    # Text of decisions that the authority can make
    decisions = [
        "no modificar el dinero obtenido por impuestos.",
        "multiplicar el monto total reportado por",
        " y apropiarse de un ",
        "% del total."
    ]

    maxdistance1 = len(reference_texts[0])
    maxdistance2 = len(reference_texts[1])
    allowed_error_rates = [0, 0.99]
    contact_template = "real_effort2/Contactenos.html"

    
class Subsession(BaseSubsession):
    # Executed when the session is created
    def creating_session(self):
        # k is a scalar that will allow to randomize the audits

        for p in self.get_players():
            k = random.randint(1, 100)/100
            p.audit = k <= self.session.config["audit_prob"]
    

class Group(BaseGroup):
    total_report = models.CurrencyField()
    total_contribution = models.CurrencyField()
    total_earnings = models.CurrencyField()
    individual_share = models.CurrencyField()
    temp = models.IntegerField()

    # ID of randomly-chosen authority player
    authority_ID = models.IntegerField()

    # Does the authority decide to multiply the reported income by the multiplier?
    # This applies to both mode 1 and mode 2 choice 1
    authority_multiply = models.BooleanField()

    # Does the authority decide on mode 2 choice (appropriate a percentage of the money for
    # him/herself)?
    auth_appropriate = models.BooleanField()
    appropriation = models.CurrencyField()

    # main parameters
    multiplier = models.FloatField() # public goods multiplier
    authority = models.StringField() # type of authority
    appropriation_percent = models.FloatField() # percentage the authority can/will appropiate
    tax_percent = models.FloatField() # income percentage that goes for taxes
    penalty_percent = models.FloatField() # income percentage that goes as penalty for bad audit
    transcription_required = models.BooleanField() # True if required, else False
    treatment_tag = models.StringField() # tag of current treatment
    spanish = models.BooleanField() # True if spanish, else False
    transcription_difficulty = models.IntegerField()


class Player(BasePlayer):
    task_earnings = models.CurrencyField()
    income_before_taxes = models.CurrencyField()
    income_after_taxes = models.CurrencyField()
    income_after_audit = models.CurrencyField()
    transcribed_text = models.LongStringField()
    levenshtein_distance = models.IntegerField()
    ratio = models.FloatField()
    contribution = models.CurrencyField(min = 0, initial = -1)
    endowment = models.CurrencyField()
    spanish = models.BooleanField()
    done = models.BooleanField()
    transcriptionDone = models.BooleanField()
    round_payoff = models.CurrencyField()
    chosen_round = models.IntegerField()
    income = models.CurrencyField()
    refText = models.LongStringField()
    audit = models.BooleanField()

real_effort2/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api
import otree.forms

import otree.api
from otree.api import Currency as c, currency_range

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()

class Form(otree.forms.Form):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

real_effort2/templates/real_effort2/Audit.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Auditoría
{% endblock %}

{% block content %}
    {% if fail %}
        <p>¡Has sido seleccionado para la auditoría!<br/><br/>Tu ingreso fue de {{ correctIncome }}, y reportaste
            {{ reportedIncome }}. Has sido penalizado con un {{ penalty }}% de tu
            ingreso restante después de pagar impuestos. <br/><br/>Por lo tanto, tu ingreso ahora es de {{ newIncome }}.
    {% else %}
        <p>¡Has sido seleccionado para la auditoría! Como reportaste correctamente tu ingreso, no se te aplica la penalidad.</p>
{% endif %}

    {% next_button %}
    <p>
        {% include Constants.contact_template %}
    </p>

{% endblock %}

real_effort2/templates/real_effort2/Authority.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
<head>
<style>
h2 {
        color: #F8F4EE;
}
</style>
</head>
<body>
    <p style="font-size:15px; color:#CD853F;" align="right">Period {{ round_num }}</p> <h1>Autoridad</h1>
    <h2>Código: a2-Au-Ap</h2><br>
</body>
{% endblock %}

{% block content %}
    {% if group.spanish %}
    <b>{{ group.id_in_subsession }}</b> p: {{ player.id_in_group }}

        <p>
        Has sido escogido para ser la autoridad de tu grupo.
        Esto quiere decir que puedes escoger entre dos alternativas:
        </p>

        <br/>

        <p>
        <b>Elección 1:</b> Multiplicar el monto total recaudado por {{ mult }} para que luego
        pueda ser repartido entre todos los integrantes en partes iguales (incluyéndote).
        <br/><br/>
        <b>Elección 2:</b> Multiplicar el monto total recaudado por {{ mult }} <b>y</b>
        quedarte con {{ appropiation_percent_display }} del monto total <b>tras multiplicar</b>. Lo
        restante será repartido entre todos los integrantes (incluyéndote).
        </p>
    {% else %}
        <p>
            You have been randomly selected to be the authority within your group and have the power to make one of two
            choices:
        </p>

            <br/>

            <p>
                <b>Choice 1:</b> Multiply the total taxed income of the participants within your group by {{ mult }}.
                <br/><br/>
                <b>Choice 2:</b> Multiply the total taxed income of the participants within your group by {{ mult }} <b>AND</b>
                appropriate {{ tax }}% of the total for yourself.
            </p>

    {% endif %}
    
    <div>
        <button name="auth_appropriate" value="False" class="btn btn-primary btn-large">Elección 1</button>
        <button name="auth_appropriate" value="True" class="btn btn-primary btn-large">Elección 2</button>
    </div>


{% endblock %}

real_effort2/templates/real_effort2/AuthorityInfo.html
{% extends "global/Page.html" %}
{% load otree static %}


{% block title %}
{% if group.authority != "no authority" %}
        <p style="font-size:15px; color:#CD853F;" align="right"><br/>Ronda {{ round_num }}</p>Información sobre la autoridad
{% else %}
        <p style="font-size:15px; color:#CD853F;" align="right"><br/>Ronda {{ round_num }}</p>Información sobre la apropiación
{% endif %}
{% endblock %}

{% block content %}
    {% if group.spanish %}
    <b>{{ group.id_in_subsession }}</b> p: {{ player.id_in_group }}
        <p>
            Otro jugador fue seleccionado para ser la autoridad. Él decidió {{ decision }}
        </p>
    {% else %}
        <p>
        Another player was selected to be the "Authority", and he/she decided to {{ decision }}
        </p>
    {% endif %}
{% next_button %}
<p>
    {% include Constants.contact_template %}
</p>

    
{% endblock %}

real_effort2/templates/real_effort2/Contactenos.html
{% load otree %}
{% load staticfiles otree %}

<b>Contáctenos:</b>
<br>
<img height="2%" width="2%" src="{% static "whatsapp.png"%}"/> <a href="https://wa.me/0051985730063" target="_blank">+51 985 730 063</a>
<br>
<img height="2%" width="2%" src="{% static "gmail.png"%}"/> e2lab@up.edu.pe

real_effort2/templates/real_effort2/FinalResults.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    <p style="font-size:15px; color:#CD853F;" align="right"><br/>Period {{ round_num }}</p>
    Resultados Finales
{% endblock %}

{% block content %}
    <p>
        La tarea actual ha concluido. Se ha escogido aleatoriamente la <b>ronda {{ chosen_round }}</b>.
    </p>
    <p>
        Por lo tanto, tu pago por esta tarea es <b>{{ chosen_payoff }}</b>
    </p>
    {% next_button %}
    
{% endblock %}

real_effort2/templates/real_effort2/Instructions.html
<div class="card bg-light instructions">
    <p>
    <h2>
    Instrucciones Generales
    </h2>
    </p>


    <p>
        Bienvenido al Laboratorio de Economía Experimental (E2LabUP). Gracias por tomarte un tiempo para participar en nuestra investigación.
        Estas son instrucciones generales para la sesión. En la pantalla del ordenador se darán instrucciones específicas para la interacción y
        la toma de decisiones.
        <br><br>
        <ul>
        <li>El uso de teléfonos celulares y otros dispositivos electrónicos (como tabletas, relojes inteligentes, etc.) no está permitido.</li>
        <li>Por favor, pon tu  teléfono celular en modo silencioso y guárdalo  durante la duración del experimento.</li>
        <li>Por favor, guarda cualquier cosa que distraiga (libros, comida, papeles) durante la duración del experimento.</li>
        <li>A partir de ahora, no hables ni te comuniques de ninguna manera con otros participantes del experimento.</li>
        <li>Si hablas en voz alta, te ríes, etc. se te pedirá que dejes el experimento y no recibirás pago.</li>
        <li>Por favor, no mires las pantallas de los otros participantes.</li>
        <li>Si tienes alguna pregunta, levanta la mano y un experimentador llegará hasta tu lugar para contestar tu pregunta en privado.</li>
        <li>Durante el experimento, serás anónimamente agrupado con otro(s) participante(s) presente(s) en el laboratorio con el(los)
            que vas a interactuar a través del computador. En ningún caso serás agrupado con una computadora o un robot.</li>
        <li>Los pagos se realizarán en privado al final de la sesión.</li>
        </ul>
    </p>
    <p>
    <h3>
    Experimento de Hoy
    </h3>
    </p>
    El experimento contará con 4 bloques y cada uno consistirá de 10 rondas de decisión.
    En cada ronda, usaremos como unidad monetaria los Soles Experimentales (SOLEX). Al final de las sesión, se escogerá
    una de las rondas al azar y se te pagará lo que hayas ganado en dicha ronda. Los SOLEX de esa ronda se cambiarán a
    Soles, y recibirás S/1 por cada 5 SOLEX.
    <p>
    <br><br>
    <div align="center">
    <h3>
        MUCHAS GRACIAS POR PARTICIPAR
    </h3>
    </div>
    </p>



    </div>
</div>

real_effort2/templates/real_effort2/InstructionsB.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block content %}

<head>
<style>
h2 {
        color: #F8F4EE;
}
</style>
</head>
<body>
<div class="card bg-light instructions">
    <div class="card-body">
    
    <b>{{ group.id_in_subsession }}</b> p: {{ player.id_in_group }}

    <h3>
        Instrucciones del Bloque
    </h3>

    <p>
        <div align="justify">
        Este experimento tendrá 2 bloques y 10 rondas de decisión por bloque. Antes de cada bloque, todos los
        participantes serán asignados a un grupo de {{ Constants.players_per_group }} personas completamente al azar. Una vez formados los
        grupos, el bloque comenzará.

        <br><br>
        <ol>
            <li>Al comenzar la ronda, realizarás una tarea de transcripción que te generará ingresos en SOLEX.
                Mientras mejor sea la transcripción, mayores serán tus ingresos.</li>
            <li>Luego, reportarás tu ingreso al Estado para que se descuenten los impuestos respectivos. La tasa de
                impuestos es de {{ display_tax_perc }} de tu ingreso. Tú puedes decidir si reportas todo lo que ganaste en la tarea
                o un monto distinto.</li>
            <li>Se realizarán auditorías al azar con probabilidad {{ audit_prob }}. Si eres auditado, y reportaste ingresos menores
                a los que recibiste, se te impondrá una penalidad, la cual es descrita a detalle en la sección de <i>Pagos</i>.</li>
            <li>Con el dinero de los impuestos, el Estado “hace obras públicas” que benefician a los ciudadanos. En concreto, el
                monto total de contribuciones es multiplicado por {{ mult }} y luego es repartido por igual entre todos los
                ciudadanos. Esta transferencia se realiza sin importar quiénes
                y cuánto han contribuido.</li>
            <li>Se considera que el <i>Estado ha sido eficiente</i> si la cantidad multiplicada es repartida a todos los participantes
                en partes iguales
            </li>
        </ol>
        <br><br>
        </div>

        <H5>Pagos:</H5> Los pagos o ganancias por ronda que tendrá un participante se determinan así:
        <br><br>
        <ul>
        <li>Si tu ingreso declarado es igual a tu ingreso verdadero, tu pago de la ronda es:
            <br><br> <b>Pago</b> = Ingreso neto de impuestos + Ganancia por la obra pública.<br><br></li>
        <li>Si tu ingreso declarado NO es igual a tu ingreso pero NO eres auditado, tu pago de la ronda es:
            <br><br> <b>Pago</b> = Ingreso neto de impuestos + Ganancia por la obra pública + Ingreso no declarado.<br><br></li>
        <li>Si tu ingreso declarado NO es igual a tu ingreso pero SÍ eres auditado, tu pago de la ronda es:
            <br><br> <b>Pago</b> = Ganancia por la obra pública + (100% - {{ penalty }})*(Ingreso antes de impuestos - Impuestos sobre Ingreso declarado) 
        </ul>
        El resultado de la ronda se muestra al terminar cada ronda.
        <br><br>
        {% if group.authority != "no authority"  %}
            <h5>Autoridad:</h5> En esta ronda, se escogerá a un participante para que sea la Autoridad y tome una decisión con respecto a la
            eficiencia del Estado: tendrá la opción de tomar {{ appropiation_percent_display }} de lo recaudado tras ser multiplicado
            para sí mismo o repartir lo multiplicado a todos en partes iguales.
            <br><br>
        {% else %}
            {% if group.appropriation_percent != 0  %}
                <h5>Eficiencia del Estado:</h5> En esta ronda, uno de los participantes será 
                elegido aleatoriamente para recibir {{ appropiation_percent_display }} de lo recaudado 
                tras ser multiplicado.
            {% endif %}
        {% endif %}
    </p>
    <p>
        <h5>Cambios por Ronda: </h5>
        Debes estar atento a las indicaciones, ya que habrán cambios en:<br><br>
        <ul>
            {% if group.authority == "no authority" %}
                <li><b>Autoridad:</b> En algunas rondas, un participante puede ser elegido aleatoriamente para que sea la Autoridad y tome una decisión con respecto a la
                eficiencia del Estado: tendrá la opción de tomar una parte adicional de lo recaudado tras ser 
                multiplicado para sí mismo o repartir lo multiplicado a todos en partes iguales.              
                </li>
                <li><b>Eficiencia del Estado:</b> En algunas rondas donde no haya autoridad, uno
                de los participantes puede ser elegido aleatoriamente para quedarse con una parte adicional
                de lo recaudado tras ser multiplicado. En otras rondas, puede haber un participante que 
                se encargue de multiplicar lo recaudado, pero no pueda tomar una parte para sí mismo.</li>
            {% else %}
                <li><b>Autoridad:</b> En algunas rondas, puede no haber Autoridad.</li>
                <li><b>Eficiencia del Estado:</b> En algunas rondas donde no haya autoridad, uno de los participantes puede ser elegido aleatoriamente para recibir
                una parte adicional de lo recaudado tras ser multiplicado. En otras rondas, puede haber un participante que se encargue de multiplicar lo recaudado,
                pero no pueda tomar una parte para sí mismo.</li>
            {% endif %}
            <li><i><b>Importante:</b></i> Si la autoridad o participante elegido toma una parte de lo multiplicado, 
            lo restante será dividido en partes iguales entre todos los participantes, incluyendo a este mismo participante.
            </li> 
        </ul>
        De ocurrir algún cambio, las instrucciones previas a esta sección se actualizarán según corresponda.
    </p>
    </div>
</div>
</body>
{% next_button %}
<p>
    {% include Constants.contact_template %}
</p>

{% endblock %}

real_effort2/templates/real_effort2/Introduction.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}

{% endblock %}

{% block content %}

    {% include Constants.instructions_template %}

    {% next_button %}
    <p>
        {% include Constants.contact_template %}
    </p>

{% endblock %}

real_effort2/templates/real_effort2/NoAuthority.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
<head>
<style>
h2 {
        color: #F8F4EE;
}
</style>
</head>
<body>
    <p style="font-size:15px; color:#CD853F;" align="right">Period {{ round_num }}</p>    <h1>Estado sin Autoridad</h1>
{% if mult == 2 %}
    <h2>Código: a2-Au-Nap</h2><br>
{% endif %}
{% if mult == 1.5 %}
    <h2>Código: a1.5-Au-Nap</h2><br>
{% endif %}
</body>
{% endblock %}

{% block content %}
    {% if group.spanish %}
    <b>{{ group.id_in_subsession }}</b> p: {{ player.id_in_group }}

        <p>
            Has sido escogido para multiplicar el monto total reportado por {{ mult }} para que luego
            pueda ser repartido entre todos los integrantes en partes iguales (incluyéndote).
        </p>
        {% if group.appropriation_percent != 0 %}
            <p>
               Asimismo, fuiste elegido para recibir {{ appropiation_percent_display }} de la cantidad total 
               recaudada tras ser multiplicada.
            </p>
            <div>
                <button name="auth_appropriate" value="True" class="btn btn-primary btn-large">Multiplicar y recibir</button>
            </div>
        {% else %}
            <div>
                <button name="auth_appropriate" value="False" class="btn btn-primary btn-large">Multiplicar</button>
            </div>
        {% endif %}

    {% else %}
        <p>
            You have been randomly selected to be the authority within your group and have been granted the power to
            multiply the total taxed income of the participants within your group by {{ mult }}.
        </p>
    {% endif %}

{% endblock %}

real_effort2/templates/real_effort2/ReportIncome.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Reporte de Ingresos
{% endblock %}

{% block content %}
    {% if group.spanish %}
        {% if transcribe_on %}
        <p> La precisión de tu transcripción fue de {{ display_ratio }}%.</p>
        <p>Por lo tanto, tu ingreso es de {{ display_income }}. ({{display_ratio}}% de {{ endowment }}).
        </p>
        {% else %}
        <p> Tu ingreso es {{ display_income }}.</p>
        {% endif %}
        <p>
            <b>La tasa impositiva es {{ tax }}% </b> </p>
        <p>
            En el siguiente recuadro, ingresa el monto que reportarás como ingreso.
        </p>
        {% formfield player.contribution label="¿Cuál es el monto que reportarás como ingreso?" %}
         <p> Recuerda que el monto total recolectado de tu grupo será multiplicado por {{ mult }} y luego será divido entre todos los miembros del grupo, sin importar cuánto contribuyó cada uno.
        </p>
    {% else %}
        {% if transcribe_on %}
            <p>
                The accuracy of your transcription was {{ display_ratio }}%.
                <br/>
                Therefore, your income is {{ display_ratio }}% of {{ endowment }} ECUs, which is {{ display_income }} ECUs.
            </p>
        {% else %}
            Your income is {{ display_income }} ECUs.
            <br/><br/>
        {% endif %}
        <p>
            Reporting Income:
            <br/>
            The tax rate is {{ tax }}%.
            <br/><br/>
            Please, in the field below, report your income for tax collection.
        </p>

        {% formfield player.contribution label="How much income will you report?" %}
    <p> Remember that the total tax collected from all group members is added together, multiplied by {{ mult }}, and then
        divided evenly among all group members, regardless of how much each contributed.
    </p>
    {% endif %}

    {% next_button %}
    <p>
        {% include Constants.contact_template %}
    </p>

{% endblock %}

real_effort2/templates/real_effort2/Transcribe.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Transcripción
{% endblock %}

{% block content %}
{% if group.spanish %}
        <p> Trascribe el siguiente texto en el recuadro.</p>
        <p> Trata de ser exacto y asegúrate de poner todas las caracteres correspondientes.</p>
    {% else %}
        <p>
        Please transcribe the text below into the input field.
        Be exact and make sure to get all characters and spaces correct.
    </p>

    {% endif %}

    <p id ="text" style="-webkit-touch-callout: none; 
    -webkit-user-select: none; 
    -khtml-user-select: none; 
    -moz-user-select: none; 
        -ms-user-select: none; 
            user-select: none; ">{{ reference_text }}</p>
    <br><br>

    {% formfield player.transcribed_text label="" %}

    {% next_button %}

    {% if debug %}
        <div class="card border-warning">
            <div class="card-body">
            <h4>Explanation for researchers (shown in debug mode only)</h4>
            <p>
                
                by clicking <a href="#" id="prefill">this link</a>
                and clicking "next".
            </p>

            <p>
                A subject can only advance to the next screen if the
                transcription is {{ required_accuracy }}% accurate.
            </p>

            </div>
        </div>

    {% endif %}
{% endblock %}

{% block scripts %}
<!-- <script>
    $(document).ready(function () {
        var referenceText = {{ reference_text|json }};
        $('#prefill').click(function () {
            $('#id_transcribed_text').val(referenceText);
        })
    });
</script> -->
{% endblock %}

real_effort2/templates/real_effort2/part2.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    <p style="font-size:15px; color:#CD853F;" align="right">{{ pgCode }}<br/>Periodo {{ round_num }}</p>
    Resultados de la transcripción y Reporte de Ingresos
{% endblock %}

{% block content %}
    {% if group.spanish %}
        {% if transcribe_on %}
        <p> La precisión de tu transcripción fue de {{ display_ratio }}%.</p>
        <p>Por lo tanto, tu ingreso es de un {{ display_ratio }}% de {{ endowment }} Solex, lo cual resulta en {{ display_income }} Solex.
        </p>
        {% else %}
        <p> Tu ingreso es  {{ display_income }} Solex.</p>
        {% endif %}
        <p>
            Reporte de Ingreso:
            <br/>
            La tasa impositiva es {{ tax }}%.
            <br/><br/>
            En el siguiente recuadro, ingresa el monto que reportarás como ingreso.
        </p>

        {% formfield player.contribution label="¿Cuál es el monto que reportarás como ingreso?" %}
        <p> Recuerda que el monto total recolectado de tu grupo será multiplicado por {{ mult }} y luego será divido entre todos los miembros del grupo, sin importar cuánto contribuyó cada uno.
    </p>
        {% endif %}
    {% else %}
        {% if transcribe_on %}
            <p>
                The accuracy of your transcription was {{ display_ratio }}%.
                <br/>
                Therefore, your income is {{ display_ratio }}% of {{ endowment }} ECUs, which is {{ display_income }} ECUs.
            </p>
        {% else %}
            Your income is {{ display_income }} ECUs.
            <br/><br/>
        {% endif %}
        <p>
            Reporting Income:
            <br/>
            The tax rate is {{ tax }}%.
            <br/><br/>
            Please, in the field below, report your income for tax collection.
        </p>

        {% formfield player.contribution label="How much income will you report?" %}
    <p> Remember that the total tax collected from all group members is added together, multiplied by {{ mult }}, and then
        divided evenly among all group members, regardless of how much each contributed.
    </p>
    {% endif %}

    {% next_button %}
    <p>
        {% include Constants.contact_template %}
    </p>

{% endblock %}